local RareDar, private = ...

--------------------------------------------------------------------------------
-- Rare mob data table used for determining whether a mob is rare or not.
--------------------------------------------------------------------------------

--- Builds a table which maps a list of values to boolean true for hash-based search.
--
-- @param list The list of elements e
-- @return the table mapping each e to true
local function Set(list)
   local set = {}
   for _, e in ipairs(list) do
      set[e] = true
   end
   return set
end

-- A table of all the rare mobs.
all_rares = Set{
   -- en
   "Raging Warmachine",
   "Defiant Assassin",
   "Gizzit",
   "Augustor",
   "Tormented Wisp",
   "Crepit Pokeit",
   "Sea Scuttler",
   "Gogrol",
   "Azagamara",
   "Vengeful Spirit",
   "Brod",
   "Marlrog",
   "Mok",
   "Pandora",
   "Pentheus",
   "Silverwood Werewolf",
   "Bahezerk",
   "Boneseeker",
   "Gnarvul",
   "Gorehorn the Mighty",
   "Gormungun",
   "Lothuu the Sad",
   "Nela Valcuthren",
   "Questing Overseer",
   "Rendfang",
   "Sentient Cruor",
   "Stone Rend",
   "Stridal",
   "Xoxtillus",
   "XT-300 Lifter",
   "Browncap Cutter",
   "Dozer",
   "Gnarl Nighthunter",
   "Lunar Shadestalker",
   "Millrush Moonstalker",
   "Scald",
   "Scarbite",
   "Stalker of Tears",
   "Stalker of the Grove",
   "Xaksha",
   "Zatzak Browncap",
   "Nightfang",
   "Rockjaw",
   "Korgek the Breaker",
   "Ghorgull",
   "Quogor",
   "Gurock",
   "Lashtail",
   "Rotwhip",
   "Shadow Harvester",
   "Bloodwhisker",
   "Gravelfist",
   "Nuhtu",
   "Granite Crawler",
   "Ironfang",
   "Blister",
   "Rivetskull",
   "Errant Wrecker",
   "Razorback Terror",
   "Barbwing",
   "Venomspitter",
   "Corpsegrinder",
   "Scarbeak",
   "Ahasa",
   "Vasyu",
   "Blackclaw",
   "Vilehide",
   "Raging Summoner",
   "Razorfang",
   "Deranged Pyromancer",
   "Fezziled the Curious",
   "Nytami",
   "Lugog the Destroyer",
   "Arumal",
   "Aelfwar Emissary",
   "Freddik the Broken",
   "Enraged Scarab",
   "Mordant Widow",
   "Kragnix the Annihilator",
   "Forgotten Sacrifice",
   "Glogg the Ravenous",
   "Hurknok",
   "Koglok",
   "Bone-Fed Ripper",
   "Jhomm The Cruel",
   "Netherworld Wanderer",
   "Emissary Kavenik",
   "Frosthide",
   "Arctic Peakstalker",
   "Mad Hogger",
   "Dagda Skullthumper",
   "Razormane",
   "Swirling Tempest",
   "Blackblood Drake",
   "Frostpaw Mauler",
   "The Predator",
   "Mangled Exile",
   "Grand Councilman Al'hazeed",
   "Lord Scaldwater",
   "Blood Bough",
   "Taziel Kanur",
   "Thagrux the Unclean",
   "Khromas the Eternal",
   "Spineclaw",
   "Experimental War Golem",
   "The Endless Broodmother",
   "Jom Turner",
   "Azumel the Screecher",
   "Acalan",
   "Anato",
   "Argyros",
   "Gaian",
   "Hyro",
   "Kallos",
   "Klacus",
   "Kleon",
   "Lalia",
   "Ligeia",
   "Lykos",
   "Myron",
   "Naeus",
   "Nikon",
   "Osmas",
   "Phocas",
   "Tephra",
   "Tricksy",
   "Thome",

   -- de workaround for now
   "Acalan",
   "Aelfwar-Abgesandter",
   "Ahasa",
   "Anato",
   "Aktischer Gipfelschleicher",
   "Argyros",
   "Arumal",
   "Augustor",
   "Azagamara",
   "Azumel der Kreischer",
   "Bahezerk",
   "Stachelschwinge",
   "Schwarzblutdraken",
   "Schwarzklaue",
   "Blase",
   "Blutast",
   "Blutbart",
   "Knochenfressender Schlitzer",
   "Knochensucher",
   "Brod",
   "Braunkappenschneider",
   "Leichenschleifer",
   "Crepit Pokeit",
   "Dagda Schädelklopfer",
   "Skeptiker-Assassine",
   "Irrer Pyromant",
   "Dozer",
   "Abgesandte Kavenik",
   "Wilder Skarabäus",
   "Wandernder Zertrümmerer",
   "Experimenteller Kriegsgolem",
   "Fezziled der Neugierige",
   "Vergessenes Opfer",
   "Freddik der Gebrochene",
   "Frosthaut",
   "Frostpranken-Raufer",
   "Gaian",
   "Ghorgull der Bote der Trankopfer",
   "Gizzit",
   "Glogg der Gefräßige",
   "Gnarl Nachtjäger",
   "Gnarvul",
   "Gogrol",
   "Bluthorn der Mächtige",
   "Gormungun",
   "Großer Ratsherr Al'hazeed",
   "Granitkriecher",
   "Schotterfaust",
   "Gurock",
   "Hurknok",
   "Hyro",
   "Eisenklaue",
   "Jhomm der Grausame",
   "Jom Turner",
   "Kallos",
   "Khromas der Ewige",
   "Klacus",
   "Kleon",
   "Koglok",
   "Korgek der Brecher",
   "Kragnix der Auslöscher",
   "Lalia",
   "Steinpeitsche",
   "Ligeia",
   "Fürst Brühwasser",
   "Lothuu der Traurige",
   "Lugog der Auslöscher",
   "Mondschattenschleicher",
   "Lykos",
   "Irrer Schweinehirt",
   "Geschundener Verbannter",
   "Marlrog",
   "Mühlstieg Mondschleicher",
   "Mok",
   "Bisskönigin",
   "Myron",
   "Naeus",
   "Nela Valcuthren",
   "Nereus",
   "Jenseits-Wanderer",
   "Nachtklaue",
   "Nikon",
   "Nuhtu",
   "Nytami",
   "Osmas",
   "Pandora",
   "Pentheus",
   "Phocas",
   "Suchender Aufseher",
   "Quogor",
   "Wütender Beschwörer",
   "Tobende Kriegsmaschine",
   "Klingenkeiler-Schrecken",
   "Messerhauer",
   "Klingenmähne",
   "Spaltzahn",
   "Nietenschädel",
   "Felskiefer",
   "Faulpeitsche",
   "Brüher",
   "Narbenschnabel",
   "Narbenbiss",
   "Seekrabbler",
   "Sentient Cruor",
   "Schattenernter",
   "Silberwald-Werwolf",
   "Stachelklaue",
   "Tränenschleicher",
   "Schleicher des Hains",
   "Steinspalter",
   "Stridal",
   "Sausender Wirbelsturm",
   "Taziel Kanur",
   "Tephra",
   "Thagrux der Unreine",
   "Die Ewige Brutmutter",
   "Der Räuber",
   "Thome",
   "Gepeinigtes Irrlicht",
   "Tricksy",
   "Vasyu",
   "Rachedurstiger Geist",
   "Giftspeier",
   "Ekelhaut",
   "Xaksha",
   "Xoxtillus",
   "XT-300",
   "Zatzak Braunkapp",
}
