local RareDar, private = ...

--------------------------------------------------------------------------------
-- Rare mob data table used for determining whether a mob is rare or not.
--------------------------------------------------------------------------------

--- Builds a table which maps a list of values to boolean true for hash-based search.
--
-- @param list The list of elements e
-- @return the table mapping each e to true
local function Set(list)
   local set = {}
   for _, e in ipairs(list) do
      set[e] = true
   end
   return set
end

-- A table of all the rare mobs.
all_rares = Set{
   -- en
   "Raging Warmachine",
   "Defiant Assassin",
   "Gizzit",
   "Augustor",
   "Tormented Wisp",
   "Crepit Pokeit",
   "Sea Scuttler",
   "Gogrol",
   "Azagamara",
   "Vengeful Spirit",
   "Brod",
   "Marlrog",
   "Mok",
   "Pandora",
   "Pentheus",
   "Silverwood Werewolf",
   "Bahezerk",
   "Boneseeker",
   "Gnarvul",
   "Gorehorn the Mighty",
   "Gormungun",
   "Lothuu the Sad",
   "Nela Valcuthren",
   "Questing Overseer",
   "Rendfang",
   "Sentient Cruor",
   "Stone Rend",
   "Stridal",
   "Xoxtillus",
   "XT-300 Lifter",
   "Browncap Cutter",
   "Dozer",
   "Gnarl Nighthunter",
   "Lunar Shadestalker",
   "Millrush Moonstalker",
   "Scald",
   "Scarbite",
   "Stalker of Tears",
   "Stalker of the Grove",
   "Xaksha",
   "Zatzak Browncap",
   "Nightfang",
   "Rockjaw",
   "Korgek the Breaker",
   "Ghorgull",
   "Quogor",
   "Gurock",
   "Lashtail",
   "Rotwhip",
   "Shadow Harvester",
   "Bloodwhisker",
   "Gravelfist",
   "Nuhtu",
   "Granite Crawler",
   "Ironfang",
   "Blister",
   "Rivetskull",
   "Errant Wrecker",
   "Razorback Terror",
   "Barbwing",
   "Venomspitter",
   "Corpsegrinder",
   "Scarbeak",
   "Ahasa",
   "Vasyu",
   "Blackclaw",
   "Vilehide",
   "Raging Summoner",
   "Razorfang",
   "Deranged Pyromancer",
   "Fezziled the Curious",
   "Nytami",
   "Lugog the Destroyer",
   "Arumal",
   "Aelfwar Emissary",
   "Freddik the Broken",
   "Enraged Scarab",
   "Mordant Widow",
   "Kragnix the Annihilator",
   "Forgotten Sacrifice",
   "Glogg the Ravenous",
   "Hurknok",
   "Koglok",
   "Bone-Fed Ripper",
   "Jhomm The Cruel",
   "Netherworld Wanderer",
   "Emissary Kavenik",
   "Frosthide",
   "Arctic Peakstalker",
   "Mad Hogger",
   "Dagda Skullthumper",
   "Razormane",
   "Swirling Tempest",
   "Blackblood Drake",
   "Frostpaw Mauler",
   "The Predator",
   "Mangled Exile",
   "Grand Councilman Al'hazeed",
   "Lord Scaldwater",
   "Blood Bough",
   "Taziel Kanur",
   "Thagrux the Unclean",
   "Khromas the Eternal",
   "Spineclaw",
   "Experimental War Golem",
   "The Endless Broodmother",
   "Jom Turner",
   "Azumel the Screecher",
   "Acalan",
   "Anato",
   "Argyros",
   "Gaian",
   "Hyro",
   "Kallos",
   "Klacus",
   "Kleon",
   "Lalia",
   "Ligeia",
   "Lykos",
   "Myron",
   "Naeus",
   "Nikon",
   "Osmas",
   "Phocas",
   "Tephra",
   "Tricksy",
   "Thome",

   -- de workaround for now
   "Acalan",
   "Aelfwar-Abgesandter",
   "Ahasa",
   "Anato",
   "Aktischer Gipfelschleicher",
   "Argyros",
   "Arumal",
   "Augustor",
   "Azagamara",
   "Azumel der Kreischer",
   "Bahezerk",
   "Stachelschwinge",
   "Schwarzblutdraken",
   "Schwarzklaue",
   "Blase",
   "Blutast",
   "Blutbart",
   "Knochenfressender Schlitzer",
   "Knochensucher",
   "Brod",
   "Braunkappenschneider",
   "Leichenschleifer",
   "Crepit Pokeit",
   "Dagda Sch�delklopfer",
   "Skeptiker-Assassine",
   "Irrer Pyromant",
   "Dozer",
   "Abgesandte Kavenik",
   "Wilder Skarab�us",
   "Wandernder Zertr�mmerer",
   "Experimenteller Kriegsgolem",
   "Fezziled der Neugierige",
   "Vergessenes Opfer",
   "Freddik der Gebrochene",
   "Frosthaut",
   "Frostpranken-Raufer",
   "Gaian",
   "Ghorgull der Bote der Trankopfer",
   "Gizzit",
   "Glogg der Gefr��ige",
   "Gnarl Nachtj�ger",
   "Gnarvul",
   "Gogrol",
   "Bluthorn der M�chtige",
   "Gormungun",
   "Gro�er Ratsherr Al'hazeed",
   "Granitkriecher",
   "Schotterfaust",
   "Gurock",
   "Hurknok",
   "Hyro",
   "Eisenklaue",
   "Jhomm der Grausame",
   "Jom Turner",
   "Kallos",
   "Khromas der Ewige",
   "Klacus",
   "Kleon",
   "Koglok",
   "Korgek der Brecher",
   "Kragnix der Ausl�scher",
   "Lalia",
   "Steinpeitsche",
   "Ligeia",
   "F�rst Br�hwasser",
   "Lothuu der Traurige",
   "Lugog der Ausl�scher",
   "Mondschattenschleicher",
   "Lykos",
   "Irrer Schweinehirt",
   "Geschundener Verbannter",
   "Marlrog",
   "M�hlstieg Mondschleicher",
   "Mok",
   "Bissk�nigin",
   "Myron",
   "Naeus",
   "Nela Valcuthren",
   "Nereus",
   "Jenseits-Wanderer",
   "Nachtklaue",
   "Nikon",
   "Nuhtu",
   "Nytami",
   "Osmas",
   "Pandora",
   "Pentheus",
   "Phocas",
   "Suchender Aufseher",
   "Quogor",
   "W�tender Beschw�rer",
   "Tobende Kriegsmaschine",
   "Klingenkeiler-Schrecken",
   "Messerhauer",
   "Klingenm�hne",
   "Spaltzahn",
   "Nietensch�del",
   "Felskiefer",
   "Faulpeitsche",
   "Br�her",
   "Narbenschnabel",
   "Narbenbiss",
   "Seekrabbler",
   "Sentient Cruor",
   "Schattenernter",
   "Silberwald-Werwolf",
   "Stachelklaue",
   "Tr�nenschleicher",
   "Schleicher des Hains",
   "Steinspalter",
   "Stridal",
   "Sausender Wirbelsturm",
   "Taziel Kanur",
   "Tephra",
   "Thagrux der Unreine",
   "Die Ewige Brutmutter",
   "Der R�uber",
   "Thome",
   "Gepeinigtes Irrlicht",
   "Tricksy",
   "Vasyu",
   "Rachedurstiger Geist",
   "Giftspeier",
   "Ekelhaut",
   "Xaksha",
   "Xoxtillus",
   "XT-300",
   "Zatzak Braunkapp",

   -- fr workaround for now
   "Raging Warmachine",
   "Assassin Defiant",
   "Gizzit",
   "Augustor",
   "Feu-follet tourment�",
   "Crepit Pokeit",
   "Naufrageur",
   "Gogrol",
   "Azagamara",
   "Esprit vengeur",
   "Brod",
   "Marlrog",
   "Mok",
   "Pandora",
   "Pentheus",
   "Loup-garou",
   "Bahezerk",
   "Chercheur d'os",
   "Gnarvul",
   "Corne-�-charpie le Puissant",
   "Gormungun",
   "Lothuu le Triste",
   "Nela Valcuthren",
   "Superviseur en qu�te",
   "Croc-d�chiqueteur",
   "Sentient Cruor",
   "D�chire-pierre",
   "Stridal",
   "Xoxtillus",
   "XT-300",
   "Trancheur Coiffebrune",
   "Dozer",
   "Gnarl Chassenuit",
   "Guetteur d'ombre lunaire",
   "Guetteur-de-lune de Millrush",
   "Scald",
   "Scarbite",
   "Guetteur de larmes",
   "Guetteur du bosquet",
   "Xaksha",
   "Zatzak Coiffebrune",
   "Croc noir",
   "M�choire � roche",
   "Korgek le Briseur",
   "Ghorgull le Faiseur de Libations",
   "Quogor",
   "Gurock",
   "Flagellateur",
   "Fouet-pourri",
   "Moissoneur de l'Ombre",
   "Chair-Khan",
   "Grossepogne",
   "Nuhtu",
   "Rampant de Granite",
   "Croc-de-Fer",
   "Cloque",
   "Cr�ne rivet�",
   "Naufrageur errant",
   "Terreur boueuse",
   "Barbail�e",
   "Crache-venin",
   "Hache-cadavre",
   "Bec-balafr�",
   "Ahasa",
   "Vasyu",
   "Pincenoire",
   "Vilepeau",
   "Invocateur rageur",
   "Croc ac�r�",
   "Pyromancienne troubl�e",
   "Feddil le Curieux",
   "Nytami",
   "Lugog le Destructeur",
   "Arumal",
   "�missaire d'Aelfwar",
   "Freddik le Bris�",
   "Scarab�e enrag�",
   "Veuve de Mordant",
   "Kragnix l'Annihilateur",
   "Sacrifice oubli�",
   "Glogg l'Affam�",
   "Hurknok",
   "Koglok",
   "�ventreur mangeur d'os",
   "Jhomm le Cruel",
   "Vagabond du N�ant",
   "�missaire Kavenik",
   "Peau-de-gel",
   "Guetteur de pic arctique",
   "Hogger le d�traqu�",
   "Dagda Gourme-cr�ne",
   "Crini�re ac�r�e",
   "Temp�te tourbillonnante",
   "Drake Sang-noir",
   "Mutileur Pattegel",
   "Le Pr�dateur",
   "Exil estropi�",
   "Grand conseiller Al'hazeed",
   "Seigneur Dahmar des Thermolacs",
   "Rameau-Sanglant",
   "Taziel Kanur",
   "Thagrux le Malpropre",
   "Khromas l'�ternel",
   "Griff�chine",
   "Golem de guerre exp�rimental",
   "Matriarche �ternelle",
   "Jom Turner",
   "Azumel le Crisseur",
   "Gaian",
   "Kleon",
   "Myron",
   "Phocas",
   "Hyro",
   "Nereus",
   "Naeus",
   "Lykos",
   "Charlie",
   "Akalan",
   "Anator",
   "Ligeia",
   "Osmas",
   "Argyros",
   "Tephra",
   "Lalia",
   "Nikon",
   "Klacus",
   "Kallos",
   "Thome",
   -- RU бета тест by Геральт[Флай]@Акилиос
   "Гиззит",
"Августор",
"Страдающий огонек",
"Крипит Покит",
"Морской попрыгун",
"Гогрол",
"Азагамара",
"Мстительный дух",
"Брод",
"Марлрог",
"Мок",
"Пандора",
"Пентий",
"Оборотень Серебристого Леса",
"Байзерк",
"Костеискатель",
"Гнарвул",
"Могучий рогач",
"Гормунган",
"Лотху Печальный",
"Нела Валькатрен",
"Повелитель заданий",
"Разрывающий клык",
"Ожившая кровь",
"Каменный клюв",
"Шагун",
"Ксоктиллус",
"XT-300",
"Коричневый резчик",
"Бульдозер",
"Ночной охотник гнаров",
"Лунный тенеход",
"Мельничный лунолов",
"Ошпаренный",
"Шрамокус",
"Следопыт плача",
"Сталкер Рощи",
"Ксакша",
"Шапка Затзака",
"Камнегрызы",
"Коргек Громила",
"Горгула, мастер возлияний",
"Квогор",
"Гарок",
"Плетехвост",
"Гнилоплеть",
"Теневой жнец",
"Кровоус",
"Гравийный Кулак",
"Нухту",
"Гранитный ползун",
"Железноклык",
"Пузырь",
"Клепаный Череп",
"Блуждающий крушитель",
"Ужасный секач",
"Шипокрыл",
"Ядоплюй",
"Трупомол",
"Шрамоклюв",
"Ахаса",
"Вэсью",
"Чернолапы",
"Злобнохват",
"Бешеный призыватель",
"Бритвозуб",
"Безумный пиромант",
"Феззилед Любознательный",
"Нитами",
"Лугог Разрушитель",
"Арумал",
"Посол Аэльваров Лунной Тени",
"Фреддик Поломашка",
"Взбесившийся скарабей",
"Едкая королева",
"Крагникс-искоренитель",
"Глогг Прожора",
"Забытая жертва",
"Харкнок",
"Коглок",
"Костежорка-потрошительница",
"Джомм Жестокий",
"Странник из преисподней",
"Посланец Кавеник",
"Ледошкур",
"Арктический охотник за вершинами",
"Сумасшедшая молотилка",
"Дагда Черепомес",
"Вепреед",
"Вьющаяся буря",
"Чернокровый дракк",
"Морозный коготь-мучитель",
"Хищник",
"Истерзанный изгой",
"Верховный советник Аль'хазид",
"Лорд Шпар",
"Кроводрев",
"Тазиэль Канур",
"Тагрукс Нечистый",
"Хромас Вечный",
"Хребтоклык",
"Экспериментальный боевой голем",
"Праматерь Вечного Двора",
"Джом Тернер",
"Азумель Хрипун",
}
